name: winace
title: WinACE (WINE)
summary: This is a GUI client for Wolfpack Empire
description: |
 While Empire is possessed of a great deal of complexities, with a bit of effort, it has proven to be the one definitive Internet experience for a great deal of people. Empire is the pinnacle of strategy games in today's world. There is none better. All the information needed to become involved is available here, the official site for the game of Empire.
adopt-info: notepad-plus-plus

icon:  EmpireMap_Icon2.png

confinement: strict
grade: stable
architectures:
  - build-on: amd64
base: core20
compression: lzo

plugs:
  wine-runtime-c20:
    interface: content
    target: $SNAP/wine-runtime
    default-provider: wine-platform-runtime-core20
  wine-7-devel:
    interface: content
    target: $SNAP/wine-platform
    default-provider: wine-platform-7-devel-core20

environment:
  WINEDLLOVERRIDES: "mscoree,mshtml=" # Prevent pop-ups about Wine Mono and Wine Gecko
  RUN_EXE: "$SNAP_USER_DATA/winace/setup.exe"
  SOMMELIER_KEEP_CWD: "1" # Don't change the working directory so relative paths still work
  NO_AT_BRIDGE: "1" # Fix yad error Failed to connect to socket /tmp/dbus-xxx: No such file or directory
  DISABLE_WAYLAND: "1" # Fix gtk decoration under wayland session
  SYSTEM_WGETRC: $SNAP/wine-runtime/etc/wgetrc

apps:
  winace:
    extensions: [ gnome-3-38 ]
    command: bin/sommelier run-exe
    plugs:
      - opengl
      - home
      - network
      - hardware-observe
      - process-control
      - cups-control
      - removable-media
    desktop: usr/share/applications/winace.desktop
  # The wine command can be used to run applications inside the wine
  # environment that this snap uses.
  #
  # For example, users can configure the wine environment of this snap
  # by running `myapp.wine winecfg`.
  wine:
    extensions: [ gnome-3-38 ]
    command: bin/sommelier
    plugs:
      - home
      - network
      - hardware-observe
      - process-control
      - cups-control
      - removable-media
  # The winetricks command can be used to run winetricks inside the wine
  # environment that this snap uses.
  winetricks:
    extensions: [ gnome-3-38 ]
    command: bin/sommelier winetricks
    plugs:
      - network

parts:
  winace:
    plugin: nil
    source: ./snap/local/src
    override-build: |
      snapcraftctl build
      set -ex
      ver=$(wget 2>/dev/null https://github.com/notepad-plus-plus/notepad-plus-plus/releases -qSO- | grep -Eo ".*.x6" | head -1 | grep -Po "(\d+\.)+\d+")
      snapcraftctl set-version "$ver"
      ./dl_npp
    stage:
      - bin
      - usr
      - wine-platform
      - wine-runtime
      - winedata
      - sommelier
    build-packages: [wget]
  # The sommelier script helps you snap Windows applications using Wine. It
  # initializes and configures Wine and installs the Windows application.
  sommelier:
    plugin: make
    source: https://github.com/mmtrt/sommelier-core.git
    source-branch: "tmp-core20"

  # This reverts changes from https://github.com/snapcore/snapcraft/pull/3586
  fix-fontconfig:
    plugin: nil
    after: [gnome-3-38-extension]
    override-prime: |
      sed -i '/snap-package/,+1d' $SNAPCRAFT_PRIME/snap/command-chain/desktop-launch

  fix-bindtext:
    plugin: nil
    after: [gnome-3-38-extension]
    override-prime: |
      sed -i "$(grep -in bindtext $SNAPCRAFT_PRIME/snap/command-chain/desktop-launch | cut -d':' -f1 | tail -2 | head -1)d" $SNAPCRAFT_PRIME/snap/command-chain/desktop-launch
      sed -i "$(grep -in bindtext $SNAPCRAFT_PRIME/snap/command-chain/desktop-launch | cut -d':' -f1 | tail -1)d" $SNAPCRAFT_PRIME/snap/command-chain/desktop-launch
